/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea3_prolog_juanrafaelv;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuanRa
 */
public class Vista2 extends javax.swing.JFrame {

    /**
     * Creates new form Vista2
     */
    public Vista2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableF = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7:0", "", null, null, null, null},
                {"7:55", null, null, null, null, null},
                {"8:50", null, null, null, null, null},
                {"9:45", null, null, null, null, null},
                {"10:40", null, null, null, null, null},
                {"12:30", null, null, null, null, null},
                {"13:25", null, null, null, null, null},
                {"14:20", null, null, null, null, null},
                {"15:10", null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista2().setVisible(true);
            }
        });
    }
    public void actualizaTabla(String info, String hora, String dia){
        /*if (listaMaterias!=null&& !listaMaterias.isEmpty()){
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            int cFilas = modelo.getRowCount();
            int cont = 0;
            while(cont != cFilas){
                modelo.removeRow(0); 
                cont+=1;
            }
            Object[] fila = new Object[modelo.getColumnCount()];
            for(int i = 0; i < listaMaterias.size();i++){
                String a = (String) listaMaterias.get(i);
                    fila[0] = false;
                    fila[1] = a;
                modelo.addRow(fila);
            }
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            int cFilas = modelo.getRowCount();
            int cont = 0;
            while(cont != cFilas){
                modelo.removeRow(0); 
                cont+=1;
            }
        }*/
           DefaultTableModel tableModel = (DefaultTableModel)jTableF.getModel();
                    int fils = tableModel.getRowCount();
                    int i = 0;
                    
                    while(i<fils) {
                            if(hora.equalsIgnoreCase(tableModel.getValueAt(i,0).toString())){
                                //tableModel.setValueAt(info, i, 1);
                                int cols = tableModel.getColumnCount();
                                int j = 1;
                                while(j<cols) {
                                    if(dia.equalsIgnoreCase(tableModel.getColumnName(j))){
                                        tableModel.setValueAt(info, i, j);
                                        break;
                                    }
                                    else{
                                        j++;
                                    }
                                }
                                break;
                            }
                            else{
                                i++;
                            }

                    }
    }
    
                    
                    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableF;
    // End of variables declaration//GEN-END:variables
}
